version: 0.5.{build}
os: Visual Studio 2015
configuration: Release
environment:
  COVERALLS_REPO_TOKEN:
    secure: hUwrEfRQVIP+rOtSr+P+5lQ0ILHSnL4aycCsmCan2Qty8v7RPtrle4qMZTs4RvMM
  GITHUB_PERSONAL_ACCESS_TOKEN:
    secure: Jmpeow5aAcDhUHkwac/AC6MzQciGc9TLgrp5oz4U0gyAwCWGqqxJhmjz3AVrWp/V	
install:
- cmd: choco install resharper-clt.portable

nuget:
  account_feed: false
  project_feed: false
  
before_build:
- cmd: nuget restore .\src\BadgesSharp.sln

build:
  project: src\BadgesSharp.sln
  verbosity: minimal

after_build:
- cmd: >-    
    "C:\Program Files (x86)\Microsoft Fxcop 10.0\FxCopCmd.exe" /project:.\src\BadgesSharp.FxCop /out:.\tools\fxcop-report.xml
    
    .\src\BadgesSharpCmd\bin\Release\BadgesSharpCmd.exe -o giacomelli -r BadgesSharp -b FxCop -c ".\tools\fxcop-report.xml" -a %GITHUB_PERSONAL_ACCESS_TOKEN%
    
    .\tools\StyleCopCmd\Net.SF.StyleCopCmd.Console\StyleCopCmd.exe -sf .\src\BadgesSharp.sln --styleCopSettingsFile .\src\Settings.StyleCop -of .\tools\stylecop-report.xml --ignoreFilePattern .+Test\.cs
    
    .\src\BadgesSharpCmd\bin\Release\BadgesSharpCmd.exe -o giacomelli -r BadgesSharp -b StyleCop -c ".\tools\stylecop-report.violations.xml" -a %GITHUB_PERSONAL_ACCESS_TOKEN%
    
    C:\ProgramData\chocolatey\lib\resharper-clt.portable\tools\dupfinder.exe /output=.\tools\dupFinder-Report.xml /show-text /exclude=**\*Test.cs;**\*.feature.cs;**\BundleConfig.cs .\src\BadgesSharp.sln
    
    .\\src\BadgesSharpCmd\bin\Release\BadgesSharpCmd.exe -o giacomelli -r BadgesSharp -b DupFinder -c .\tools\dupFinder-Report.xml -a %GITHUB_PERSONAL_ACCESS_TOKEN%

test_script:
- ps: >-
    .\src\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:nunit-console.exe -register:user "-targetargs:""src\BadgesSharp.Domain.UnitTests\bin\$env:CONFIGURATION\BadgesSharp.Domain.UnitTests.dll","src\BadgesSharp.Extensions.UnitTests\bin\$env:CONFIGURATION\BadgesSharp.Extensions.UnitTests.dll","src\BadgesSharp.Infrastructure.Framework.UnitTests\bin\$env:CONFIGURATION\BadgesSharp.Infrastructure.Framework.UnitTests.dll","src\BadgesSharp.Infrastructure.Threading.UnitTests\bin\$env:CONFIGURATION\BadgesSharp.Infrastructure.Threading.UnitTests.dll"" /noshadow" -filter:"+[BadgesSharp.Domain]* +[BadgesSharp.Extensions]* +[BadgesSharp.Infrastructure.Framework]* +[BadgesSharp.Infrastructure.Threading]*" -output:opencoverCoverage.xml

    .\src\packages\coveralls.net.0.6.0\tools\csmacnz.Coveralls.exe --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID
artifacts:
  - path: .\tools\fxcop-report.xml
    name: FxCop-Report  
  - path: .\tools\stylecop-report.xml
    name: StyleCop-Report     
  - path: .\tools\dupFinder-report.xml
    name: DupFinder-report 