//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BadgesSharp.Infrastructure.Framework.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BadgesSharp.Infrastructure.Framework.Globalization.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Coverage.
        /// </summary>
        internal static string CodeCoverage {
            get {
                return ResourceManager.GetString("CodeCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DupFinder.
        /// </summary>
        internal static string DupFinder {
            get {
                return ResourceManager.GetString("DupFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FxCop.
        /// </summary>
        internal static string FxCop {
            get {
                return ResourceManager.GetString("FxCop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plato.
        /// </summary>
        internal static string PlatoMaintainability {
            get {
                return ResourceManager.GetString("PlatoMaintainability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleCop.
        /// </summary>
        internal static string StyleCop {
            get {
                return ResourceManager.GetString("StyleCop", resourceCulture);
            }
        }
    }
}
