using HelperSharp;

namespace BadgesSharp.Builders
{
    /// <summary>
    /// The total badges generated by BadgesSharp badge builder.
    /// <remarks>
    /// It's a special badge used on BadgesSharp site and repository.
    /// </remarks>
    /// </summary>
    public class TotalGeneratedBadgesBadgeBuilder : BadgeBuilderBase
    {
        #region Constructors        
        /// <summary>
        /// Initializes a new instance of the <see cref="TotalGeneratedBadgesBadgeBuilder"/> class.
        /// </summary>
        /// <param name="badgeService">The badge service.</param>
        public TotalGeneratedBadgesBadgeBuilder(BadgeService badgeService) : base("BadgesSharp")
        {
            Status = BadgeStatus.Success;
            Style.Success.Text = "{0:N0} badges generated".With(badgeService.CountBadges());
        }
        #endregion
    }
}
